spring:
  application:
    name: songjourn
  datasource:
    url: jdbc:postgresql://localhost:5432/songjourndb
#    username: ${POSTGRES_USER_NAME}
    username: songjourn
#    password: ${POSTGRES_PASSWORD}
    password: secret
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /songjourn
  sql:
    init:
      data-locations: classpath:data.sql
      platform: postgresql
      mode: always
  output:
    ansi:
      enabled: always
server:
  port: 8011
