INSERT INTO countries (country_name) VALUES ('Albania');
INSERT INTO countries (country_name) VALUES ('Argentina');
INSERT INTO countries (country_name) VALUES ('Armenia');
INSERT INTO countries (country_name) VALUES ('Australia');
INSERT INTO countries (country_name) VALUES ('Austria');
INSERT INTO countries (country_name) VALUES ('Azerbaijan');
INSERT INTO countries (country_name) VALUES ('The Bahamas');
INSERT INTO countries (country_name) VALUES ('Belarus');
INSERT INTO countries (country_name) VALUES ('Belgium');
INSERT INTO countries (country_name) VALUES ('Bosnia and Herzegovina');
INSERT INTO countries (country_name) VALUES ('Brazil');
INSERT INTO countries (country_name) VALUES ('Bulgaria');
INSERT INTO countries (country_name) VALUES ('Canada');
INSERT INTO countries (country_name) VALUES ('China');
INSERT INTO countries (country_name) VALUES ('Colombia');
INSERT INTO countries (country_name) VALUES ('Costa Rica');
INSERT INTO countries (country_name) VALUES ('Croatia');
INSERT INTO countries (country_name) VALUES ('Cuba');
INSERT INTO countries (country_name) VALUES ('Cyprus');
INSERT INTO countries (country_name) VALUES ('Czech Republic');
INSERT INTO countries (country_name) VALUES ('Denmark');
INSERT INTO countries (country_name) VALUES ('Dominican Republic');
INSERT INTO countries (country_name) VALUES ('Estonia');
INSERT INTO countries (country_name) VALUES ('Finland');
INSERT INTO countries (country_name) VALUES ('France');
INSERT INTO countries (country_name) VALUES ('Georgia');
INSERT INTO countries (country_name) VALUES ('Germany');
INSERT INTO countries (country_name) VALUES ('Greece');
INSERT INTO countries (country_name) VALUES ('Guatemala');
INSERT INTO countries (country_name) VALUES ('Haiti');
INSERT INTO countries (country_name) VALUES ('Honduras');
INSERT INTO countries (country_name) VALUES ('Hungary');
INSERT INTO countries (country_name) VALUES ('Iceland');
INSERT INTO countries (country_name) VALUES ('India');
INSERT INTO countries (country_name) VALUES ('Ireland');
INSERT INTO countries (country_name) VALUES ('Israel');
INSERT INTO countries (country_name) VALUES ('Italy');
INSERT INTO countries (country_name) VALUES ('Jamaica');
INSERT INTO countries (country_name) VALUES ('Japan');
INSERT INTO countries (country_name) VALUES ('Kenya');
INSERT INTO countries (country_name) VALUES ('Korea, South');
INSERT INTO countries (country_name) VALUES ('Latvia');
INSERT INTO countries (country_name) VALUES ('Lithuania');
INSERT INTO countries (country_name) VALUES ('Luxembourg');
INSERT INTO countries (country_name) VALUES ('Malta');
INSERT INTO countries (country_name) VALUES ('Mexico');
INSERT INTO countries (country_name) VALUES ('Moldova');
INSERT INTO countries (country_name) VALUES ('Montenegro');
INSERT INTO countries (country_name) VALUES ('Morocco');
INSERT INTO countries (country_name) VALUES ('Netherlands');
INSERT INTO countries (country_name) VALUES ('New Zealand');
INSERT INTO countries (country_name) VALUES ('Nigeria');
INSERT INTO countries (country_name) VALUES ('North Macedonia');
INSERT INTO countries (country_name) VALUES ('Norway');
INSERT INTO countries (country_name) VALUES ('Poland');
INSERT INTO countries (country_name) VALUES ('Portugal');
INSERT INTO countries (country_name) VALUES ('Romania');
INSERT INTO countries (country_name) VALUES ('Russia');
INSERT INTO countries (country_name) VALUES ('San Marino');
INSERT INTO countries (country_name) VALUES ('Senegal');
INSERT INTO countries (country_name) VALUES ('Serbia');
INSERT INTO countries (country_name) VALUES ('Slovakia');
INSERT INTO countries (country_name) VALUES ('Slovenia');
INSERT INTO countries (country_name) VALUES ('South Africa');
INSERT INTO countries (country_name) VALUES ('Spain');
INSERT INTO countries (country_name) VALUES ('Sweden');
INSERT INTO countries (country_name) VALUES ('Switzerland');
INSERT INTO countries (country_name) VALUES ('Turkey');
INSERT INTO countries (country_name) VALUES ('Ukraine');
INSERT INTO countries (country_name) VALUES ('United Kingdom');
INSERT INTO countries (country_name) VALUES ('United States');
INSERT INTO countries (country_name) VALUES ('Venezuela');
INSERT INTO countries (country_name) VALUES ('Puerto Rico');
INSERT INTO countries (country_name) VALUES ('Congo');
INSERT INTO tracks (country_id, spotify_id) VALUES (35, '0gzqZ9d1jIKo9psEIthwXe');
INSERT INTO tracks (country_id, spotify_id) VALUES (38, '0oWha7OKAqQwFZymfthIEV');
INSERT INTO tracks (country_id, spotify_id) VALUES (38, '0q5giEtY4wsFTwjWqswLwx');
INSERT INTO tracks (country_id, spotify_id) VALUES (11, '0Vl9aGb0dmeiCQ2ATgNK2B');
INSERT INTO tracks (country_id, spotify_id) VALUES (37, '0z3Voyxi0FH0SQBc7c4wri');
INSERT INTO tracks (country_id, spotify_id) VALUES (67, '1EjIXKhNHI00ZLMRpS8iz8');
INSERT INTO tracks (country_id, spotify_id) VALUES (25, '1gF54htiEe5AGRiUDO4hl7');
INSERT INTO tracks (country_id, spotify_id) VALUES (70, '20I8RduZC2PWMWTDCZuuAN');
INSERT INTO tracks (country_id, spotify_id) VALUES (11, '2aGWQVK6ed2GtnZTBosCyg');
INSERT INTO tracks (country_id, spotify_id) VALUES (51, '2dLLR6qlu5UJ5gk0dKz0h3');
INSERT INTO tracks (country_id, spotify_id) VALUES (27, '2IJftBfq7pJ43tfnOR0RB3');
INSERT INTO tracks (country_id, spotify_id) VALUES (52, '2Xr1dTzJee307rmrkt8c0g');
INSERT INTO tracks (country_id, spotify_id) VALUES (70, '3AeicLnm55RqcXGBKYQolM');
INSERT INTO tracks (country_id, spotify_id) VALUES (70, '456WNXWhDwYOSf5SpTuqxd');
INSERT INTO tracks (country_id, spotify_id) VALUES (70, '4pbyDPjFgfPqFTcIMC8xpK');
INSERT INTO tracks (country_id, spotify_id) VALUES (4, '4VrWlk8IQxevMvERoX08iC');
INSERT INTO tracks (country_id, spotify_id) VALUES (47, '52Zr0sinhWTCRrQhRRY4EP');
INSERT INTO tracks (country_id, spotify_id) VALUES (2, '5Fj753yCLyWL699hiiCgoJ');
INSERT INTO tracks (country_id, spotify_id) VALUES (3, '5ikUCEXt9xjVXf8ojHne77');
INSERT INTO tracks (country_id, spotify_id) VALUES (65, '5M830cD7MNeiiwIGHzH9TV');
INSERT INTO tracks (country_id, spotify_id) VALUES (41, '5QDLhrAOJJdNAmCTJ8xMyW');
INSERT INTO tracks (country_id, spotify_id) VALUES (66, '5Xpnq4yeofsvWPSFC9rvuP');
INSERT INTO tracks (country_id, spotify_id) VALUES (53, '67Bq9jeCG30mCFG4Geeb8n');
INSERT INTO tracks (country_id, spotify_id) VALUES (37, '7anRsNjcOSrNYf2FjYopCH');
INSERT INTO tracks (country_id, spotify_id) VALUES (71, '7hDVYcQq6MxkdJGweuCtl9');
INSERT INTO tracks (country_id, spotify_id) VALUES (37, '7lMIJ4EFWRVoAIPDpeGyM3');
INSERT INTO tracks (country_id, spotify_id) VALUES (13, '2eAvDnpXP5W0cVtiI0PUxV');
INSERT INTO tracks (country_id, spotify_id) VALUES (70, '6k1I9gABiasGZiWWAosAEb');
INSERT INTO tracks (country_id, spotify_id) VALUES (70, '2AT8iROs4FQueDv2c8q2KE');
INSERT INTO tracks (country_id, spotify_id) VALUES (35, '3dYD57lRAUcMHufyqn9GcI');
INSERT INTO tracks (country_id, spotify_id) VALUES (70, '67Hna13dNDkZvBpTXRIaOJ');
INSERT INTO tracks (country_id, spotify_id) VALUES (53, '0k7jchNwc9cQM5b6vInH8A');
INSERT INTO tracks (country_id, spotify_id) VALUES (9, '5drK2kTE2mrUdV33iHWyrx');
INSERT INTO tracks (country_id, spotify_id) VALUES (27, '2xc8WSkjAp4xRGV6I1Aktb');
INSERT INTO tracks (country_id, spotify_id) VALUES (41, '5sbooPcNgIE22DwO0VNGUJ');
INSERT INTO tracks (country_id, spotify_id) VALUES (66, '4HzgLpnh5U2Id1uBHbPuQ0');
INSERT INTO tracks (country_id, spotify_id) VALUES (9, '21qnJAMtzC6S5SESuqQLEK');
INSERT INTO tracks (country_id, spotify_id) VALUES (25, '6kPpbxAtg5QNDGkgvWR30I');
INSERT INTO tracks (country_id, spotify_id) VALUES (9, '2GYHyAoLWpkxLVa4oYTVko');
INSERT INTO tracks (country_id, spotify_id) VALUES (66, '6aqNCrRA7vs7v6QvRpI50t');
INSERT INTO tracks (country_id, spotify_id) VALUES (13, '6epn3r7S14KUqlReYr77hA');
INSERT INTO tracks (country_id, spotify_id) VALUES (70, '1SKApv6ZfJ9bkUxeRObJEF');
INSERT INTO tracks (country_id, spotify_id) VALUES (65, '53tfEupEzQRtVFOeZvk7xq');
INSERT INTO tracks (country_id, spotify_id) VALUES (24, '2xaFtNhCw5Q4hn1EKsrkLv');
INSERT INTO tracks (country_id, spotify_id) VALUES (13, '0VjIjW4GlUZAMYd2vXMi3b');
INSERT INTO tracks (country_id, spotify_id) VALUES (50, '1Q0p30HuN1ADMX2CmPzIvO');
INSERT INTO tracks (country_id, spotify_id) VALUES (64, '1BLXxFPDL2BT37nHKD7KrA');
INSERT INTO tracks (country_id, spotify_id) VALUES (25, '5JdLUE9D743ob2RtgmVpVx');
INSERT INTO tracks (country_id, spotify_id) VALUES (27, '5CGPOGyyF3XvyQwyqlJH0P');
INSERT INTO tracks (country_id, spotify_id) VALUES (4, '3E7ZwUMJFqpsDOJzEkBrQ7');
INSERT INTO tracks (country_id, spotify_id) VALUES (34, '2YoPh281gD3xPnTkojVSr3');
INSERT INTO tracks (country_id, spotify_id) VALUES (3, '76OGwb5RA9h4FxQPT33ekc');
INSERT INTO tracks (country_id, spotify_id) VALUES (64, '5aIVCx5tnk0ntmdiinnYvw');
INSERT INTO tracks (country_id, spotify_id) VALUES (13, '3rUGC1vUpkDG9CZFHMur1t');
INSERT INTO tracks (country_id, spotify_id) VALUES (71, '2LKOHdMsL0K9KwcPRlJK2v');
INSERT INTO tracks (country_id, spotify_id) VALUES (71, '2QjOHCTQ1Jl3zawyYOpxh6');
INSERT INTO tracks (country_id, spotify_id) VALUES (70, '4LRPiXqCikLlN15c3yImP7');
INSERT INTO tracks (country_id, spotify_id) VALUES (71, '73RbfOTJIjHzi2pcVHjeHM');
INSERT INTO tracks (country_id, spotify_id) VALUES (69, '5oAuqB3aoXBm0nmyEKYxAU');
INSERT INTO tracks (country_id, spotify_id) VALUES (15, '0RJWhctsc1G1Hg3Ov2th7x');
INSERT INTO tracks (country_id, spotify_id) VALUES (25, '6e0LjNPkRqxIAlmmdjWSV8');
INSERT INTO tracks (country_id, spotify_id) VALUES (73, '4bNqBlJkoueiFla9YsyNg9');
INSERT INTO tracks (country_id, spotify_id) VALUES (66, '0hrBpAOgrt8RXigk83LLNE');
INSERT INTO tracks (country_id, spotify_id) VALUES (35, '6FLwmdmW77N1Pxb1aWsZmO');
INSERT INTO tracks (country_id, spotify_id) VALUES (70, '7hhclvecTpNxNNRCk7NUoc');
INSERT INTO tracks (country_id, spotify_id) VALUES (70, '1RKUoGiLEbcXN4GY4spQDx');
INSERT INTO tracks (country_id, spotify_id) VALUES (50, '5oBF1VuvCpkoZAbIiZ1u2z');
INSERT INTO tracks (country_id, spotify_id) VALUES (25, '5lBP49wdNHz8eMTIbi3bfb');
INSERT INTO tracks (country_id, spotify_id) VALUES (74, '5DlEHbXTtsbmbRjcrv4xL8');
INSERT INTO tracks (country_id, spotify_id) VALUES (24, '46QsOVy8EDjHmfCxTUQsCh');
INSERT INTO tracks (country_id, spotify_id) VALUES (70, '3wtMkvedoWMQ3XTKv7tqcZ');
INSERT INTO tracks (country_id, spotify_id) VALUES (70, '5TXAySV8WBjAIMg3lPDCLN');
INSERT INTO tracks (country_id, spotify_id) VALUES (27, '5NGsvd9Wf6fzu3Dux4DQAu');
INSERT INTO tracks (country_id, spotify_id) VALUES (70, '1EmimnysAUBhiy8rDbNN01');
INSERT INTO tracks (country_id, spotify_id) VALUES (70, '1dIvK1tfMV2UF7pWUoYgDq');