INSERT INTO countries (country_name) VALUES ('Albania');
INSERT INTO countries (country_name) VALUES ('Argentina');
INSERT INTO countries (country_name) VALUES ('Armenia');
INSERT INTO countries (country_name) VALUES ('Australia');
INSERT INTO countries (country_name) VALUES ('Austria');
INSERT INTO countries (country_name) VALUES ('Azerbaijan');
INSERT INTO countries (country_name) VALUES ('The Bahamas');
INSERT INTO countries (country_name) VALUES ('Belarus');
INSERT INTO countries (country_name) VALUES ('Belgium');
INSERT INTO countries (country_name) VALUES ('Bosnia and Herzegovina');
INSERT INTO countries (country_name) VALUES ('Brazil');
INSERT INTO countries (country_name) VALUES ('Bulgaria');
INSERT INTO countries (country_name) VALUES ('Canada');
INSERT INTO countries (country_name) VALUES ('China');
INSERT INTO countries (country_name) VALUES ('Colombia');
INSERT INTO countries (country_name) VALUES ('Costa Rica');
INSERT INTO countries (country_name) VALUES ('Croatia');
INSERT INTO countries (country_name) VALUES ('Cuba');
INSERT INTO countries (country_name) VALUES ('Cyprus');
INSERT INTO countries (country_name) VALUES ('Czech Republic');
INSERT INTO countries (country_name) VALUES ('Denmark');
INSERT INTO countries (country_name) VALUES ('Dominican Republic');
INSERT INTO countries (country_name) VALUES ('Estonia');
INSERT INTO countries (country_name) VALUES ('Finland');
INSERT INTO countries (country_name) VALUES ('France');
INSERT INTO countries (country_name) VALUES ('Georgia');
INSERT INTO countries (country_name) VALUES ('Germany');
INSERT INTO countries (country_name) VALUES ('Greece');
INSERT INTO countries (country_name) VALUES ('Guatemala');
INSERT INTO countries (country_name) VALUES ('Haiti');
INSERT INTO countries (country_name) VALUES ('Honduras');
INSERT INTO countries (country_name) VALUES ('Hungary');
INSERT INTO countries (country_name) VALUES ('Iceland');
INSERT INTO countries (country_name) VALUES ('India');
INSERT INTO countries (country_name) VALUES ('Ireland');
INSERT INTO countries (country_name) VALUES ('Israel');
INSERT INTO countries (country_name) VALUES ('Italy');
INSERT INTO countries (country_name) VALUES ('Jamaica');
INSERT INTO countries (country_name) VALUES ('Japan');
INSERT INTO countries (country_name) VALUES ('Kenya');
INSERT INTO countries (country_name) VALUES ('Korea, South');
INSERT INTO countries (country_name) VALUES ('Latvia');
INSERT INTO countries (country_name) VALUES ('Lithuania');
INSERT INTO countries (country_name) VALUES ('Luxembourg');
INSERT INTO countries (country_name) VALUES ('Malta');
INSERT INTO countries (country_name) VALUES ('Mexico');
INSERT INTO countries (country_name) VALUES ('Moldova');
INSERT INTO countries (country_name) VALUES ('Montenegro');
INSERT INTO countries (country_name) VALUES ('Morocco');
INSERT INTO countries (country_name) VALUES ('Netherlands');
INSERT INTO countries (country_name) VALUES ('New Zealand');
INSERT INTO countries (country_name) VALUES ('Nigeria');
INSERT INTO countries (country_name) VALUES ('North Macedonia');
INSERT INTO countries (country_name) VALUES ('Norway');
INSERT INTO countries (country_name) VALUES ('Poland');
INSERT INTO countries (country_name) VALUES ('Portugal');
INSERT INTO countries (country_name) VALUES ('Romania');
INSERT INTO countries (country_name) VALUES ('Russia');
INSERT INTO countries (country_name) VALUES ('San Marino');
INSERT INTO countries (country_name) VALUES ('Senegal');
INSERT INTO countries (country_name) VALUES ('Serbia');
INSERT INTO countries (country_name) VALUES ('Slovakia');
INSERT INTO countries (country_name) VALUES ('Slovenia');
INSERT INTO countries (country_name) VALUES ('South Africa');
INSERT INTO countries (country_name) VALUES ('Spain');
INSERT INTO countries (country_name) VALUES ('Sweden');
INSERT INTO countries (country_name) VALUES ('Switzerland');
INSERT INTO countries (country_name) VALUES ('Turkey');
INSERT INTO countries (country_name) VALUES ('Ukraine');
INSERT INTO countries (country_name) VALUES ('United Kingdom');
INSERT INTO countries (country_name) VALUES ('United States');
INSERT INTO countries (country_name) VALUES ('Venezuela');
INSERT INTO tracks (country_id, spotify_id) VALUES (67, '1EjIXKhNHI00ZLMRpS8iz8');
INSERT INTO tracks (country_id, spotify_id) VALUES (66, '5Xpnq4yeofsvWPSFC9rvuP');
INSERT INTO tracks (country_id, spotify_id) VALUES (71, '7hDVYcQq6MxkdJGweuCtl9');
INSERT INTO tracks (country_id, spotify_id) VALUES (53, '67Bq9jeCG30mCFG4Geeb8n');
INSERT INTO tracks (country_id, spotify_id) VALUES (70, '4pbyDPjFgfPqFTcIMC8xpK');
INSERT INTO tracks (country_id, spotify_id) VALUES (70, '20I8RduZC2PWMWTDCZuuAN');
INSERT INTO tracks (country_id, spotify_id) VALUES (2, '5Fj753yCLyWL699hiiCgoJ');
INSERT INTO tracks (country_id, spotify_id) VALUES (70, '456WNXWhDwYOSf5SpTuqxd');
INSERT INTO tracks (country_id, spotify_id) VALUES (38, '0q5giEtY4wsFTwjWqswLwx');
INSERT INTO tracks (country_id, spotify_id) VALUES (38, '0oWha7OKAqQwFZymfthIEV');
INSERT INTO tracks (country_id, spotify_id) VALUES (52, '2Xr1dTzJee307rmrkt8c0g');
INSERT INTO tracks (country_id, spotify_id) VALUES (37, '0z3Voyxi0FH0SQBc7c4wri');
INSERT INTO tracks (country_id, spotify_id) VALUES (37, '7anRsNjcOSrNYf2FjYopCH');
INSERT INTO tracks (country_id, spotify_id) VALUES (27, '2IJftBfq7pJ43tfnOR0RB3');
INSERT INTO tracks (country_id, spotify_id) VALUES (35, '0gzqZ9d1jIKo9psEIthwXe');
INSERT INTO tracks (country_id, spotify_id) VALUES (25, '1gF54htiEe5AGRiUDO4hl7');
INSERT INTO tracks (country_id, spotify_id) VALUES (65, '5M830cD7MNeiiwIGHzH9TV');
INSERT INTO tracks (country_id, spotify_id) VALUES (4, '4VrWlk8IQxevMvERoX08iC');
INSERT INTO tracks (country_id, spotify_id) VALUES (3, '5ikUCEXt9xjVXf8ojHne77');
INSERT INTO tracks (country_id, spotify_id) VALUES (11, '2aGWQVK6ed2GtnZTBosCyg');
INSERT INTO tracks (country_id, spotify_id) VALUES (11, '0Vl9aGb0dmeiCQ2ATgNK2B');
INSERT INTO tracks (country_id, spotify_id) VALUES (41, '5QDLhrAOJJdNAmCTJ8xMyW');
INSERT INTO tracks (country_id, spotify_id) VALUES (51, '2dLLR6qlu5UJ5gk0dKz0h3');
INSERT INTO tracks (country_id, spotify_id) VALUES (70, '3AeicLnm55RqcXGBKYQolM');
INSERT INTO tracks (country_id, spotify_id) VALUES (47, '52Zr0sinhWTCRrQhRRY4EP');
INSERT INTO tracks (country_id, spotify_id) VALUES (37, '7lMIJ4EFWRVoAIPDpeGyM3');